#!/usr/bin/env bash
#
# Bump the version every app reports to Home Assistant, and optionally the
# upstream Beszel version pinned alongside it.
#
# The two are independent. A packaging-only release - new app behaviour, same
# Beszel binary - bumps the app version and leaves beszel_version alone.
#
#   ./scripts/bump-version.sh 0.19.0.2                  # app version only
#   ./scripts/bump-version.sh 0.19.1 --beszel           # app version, upstream to match
#   ./scripts/bump-version.sh 0.19.0.2 --beszel=0.19.1  # app and upstream set separately
#   ./scripts/bump-version.sh --show                    # print current versions, change nothing
#   ./scripts/bump-version.sh 0.19.0.2 --dry-run        # show what would change, write nothing
#

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}" || exit 1

APP_VERSION=""
BESZEL_VERSION=""
BUMP_BESZEL=0
WRITE_CHANGELOG=1
DRY_RUN=0
SHOW_ONLY=0

usage() {
    sed -n '2,17p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    cat <<'EOF'

Options:
  --beszel            Also write beszel_version, using the app version
  --beszel=<version>  Also write beszel_version, using this version instead
  --no-changelog      Leave CHANGELOG.md alone (it is regenerated by default)
  --show              Print the current versions and exit
  -n, --dry-run       Report what would change without writing
  -h, --help          Show this help
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --beszel)       BUMP_BESZEL=1 ;;
        --beszel=*)     BUMP_BESZEL=1; BESZEL_VERSION="${1#*=}" ;;
        --no-changelog) WRITE_CHANGELOG=0 ;;
        --show)         SHOW_ONLY=1 ;;
        -n|--dry-run)   DRY_RUN=1 ;;
        -h|--help)      usage; exit 0 ;;
        -*)             echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
        *)              if [ -n "${APP_VERSION}" ]; then
                            echo "Unexpected argument: $1" >&2; usage >&2; exit 2
                        fi
                        APP_VERSION="$1" ;;
    esac
    shift
done

# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------
if [ -t 1 ]; then
    C_RED=$'\033[31m'; C_GRN=$'\033[32m'
    C_BLU=$'\033[34m'; C_DIM=$'\033[2m';  C_OFF=$'\033[0m'
else
    C_RED=""; C_GRN=""; C_BLU=""; C_DIM=""; C_OFF=""
fi

pass()  { printf '  %sPASS%s  %s\n' "${C_GRN}" "${C_OFF}" "$*"; }
info()  { printf '  %s%s%s\n' "${C_DIM}" "$*" "${C_OFF}"; }
head1() { printf '\n%s==> %s%s\n' "${C_BLU}" "$*" "${C_OFF}"; }
die()   { printf '  %sERROR%s %s\n' "${C_RED}" "${C_OFF}" "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------
APPS=""
while IFS= read -r dir; do
    [ -n "${dir}" ] || continue
    APPS="${APPS} ${dir}"
done <<EOF
$(find . -maxdepth 2 -name config.yaml -path './beszel_*' -exec dirname {} \; | sed 's|^\./||' | sort)
EOF

[ -n "${APPS## }" ] || die "No beszel_* app directories found under ${REPO_ROOT}"

config_version() { sed -nE 's/^version: "(.*)"$/\1/p' "$1/config.yaml"; }
pinned_version() { tr -d '[:space:]' < "$1/beszel_version"; }

# owner/repo, so the generated changelog link matches the one publish.yml builds
# from ${{ github.repository }}. Falls back to the url: field in config.yaml.
repo_slug() {
    local url=""
    url="$(git config --get remote.origin.url 2>/dev/null)"
    case "${url}" in
        *github.com*) ;;
        *) url="$(sed -nE 's#^url: "https://github.com/(.*)"$#\1#p' beszel_agent/config.yaml)"
           printf '%s' "${url%.git}"; return ;;
    esac
    url="${url#*github.com}"
    url="${url#:}"; url="${url#/}"
    printf '%s' "${url%.git}"
}

# BSD and GNU sed disagree about -i, and writing through the existing file keeps
# its inode and permissions rather than inheriting mktemp's 0600.
replace_in_place() {
    local file="$1" expr="$2" tmp rc
    tmp="$(mktemp)" || return 1
    sed -E "${expr}" "${file}" > "${tmp}"; rc=$?
    [ "${rc}" -eq 0 ] && cat "${tmp}" > "${file}"; rc=$?
    rm -f "${tmp}"
    return "${rc}"
}

show_versions() {
    head1 "Current versions"
    printf '  %-24s %-12s %s\n' "APP" "VERSION" "BESZEL"
    for app in ${APPS}; do
        printf '  %-24s %-12s %s\n' "${app}" "$(config_version "${app}")" "$(pinned_version "${app}")"
    done
}

# ---------------------------------------------------------------------------
# Validate
# ---------------------------------------------------------------------------
if [ "${SHOW_ONLY}" -eq 1 ]; then
    show_versions
    exit 0
fi

[ -n "${APP_VERSION}" ] || { echo "Missing version." >&2; usage >&2; exit 2; }

valid_version() {
    [[ "$1" =~ ^[0-9]+(\.[0-9]+)*$ ]]
}

valid_version "${APP_VERSION}" || die "Not a version number: ${APP_VERSION}"

if [ "${BUMP_BESZEL}" -eq 1 ] && [ -z "${BESZEL_VERSION}" ]; then
    BESZEL_VERSION="${APP_VERSION}"
fi
if [ -n "${BESZEL_VERSION}" ]; then
    valid_version "${BESZEL_VERSION}" || die "Not a version number: ${BESZEL_VERSION}"
fi

# Every app must carry a version: line, or the bump would silently skip it and
# leave the repository with apps on two different versions.
for app in ${APPS}; do
    [ -f "${app}/config.yaml" ]    || die "${app}: no config.yaml"
    [ -f "${app}/beszel_version" ] || die "${app}: no beszel_version"
    [ -n "$(config_version "${app}")" ] || die "${app}: config.yaml has no 'version: \"...\"' line"
done

SLUG="$(repo_slug)"
[ -n "${SLUG}" ] || die "Could not determine the owner/repo for the changelog link"

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------
show_versions

head1 "Bumping to ${APP_VERSION}"
if [ "${BUMP_BESZEL}" -eq 1 ]; then
    info "upstream Beszel version -> ${BESZEL_VERSION}"
else
    info "upstream Beszel version left untouched (pass --beszel to move it too)"
fi
[ "${WRITE_CHANGELOG}" -eq 1 ] && info "CHANGELOG.md regenerated to link v${APP_VERSION} (${SLUG})"
[ "${DRY_RUN}" -eq 1 ] && info "dry run - nothing will be written"

# ---------------------------------------------------------------------------
# Write
# ---------------------------------------------------------------------------
head1 "Files"
CHANGED=0
for app in ${APPS}; do
    old_app="$(config_version "${app}")"
    old_pin="$(pinned_version "${app}")"
    changes=""

    [ "${old_app}" != "${APP_VERSION}" ] && changes="${changes} config.yaml ${old_app}->${APP_VERSION}"
    if [ "${BUMP_BESZEL}" -eq 1 ] && [ "${old_pin}" != "${BESZEL_VERSION}" ]; then
        changes="${changes} beszel_version ${old_pin}->${BESZEL_VERSION}"
    fi

    if [ "${DRY_RUN}" -eq 1 ]; then
        if [ -n "${changes## }" ]; then
            info "${app}:${changes}"
            CHANGED=$((CHANGED + 1))
        else
            info "${app}: already up to date"
        fi
        continue
    fi

    replace_in_place "${app}/config.yaml" "s/^version: \".*\"$/version: \"${APP_VERSION}\"/" \
        || die "${app}: could not rewrite config.yaml"
    [ "$(config_version "${app}")" = "${APP_VERSION}" ] \
        || die "${app}: config.yaml still reports $(config_version "${app}")"

    if [ "${BUMP_BESZEL}" -eq 1 ]; then
        printf '%s\n' "${BESZEL_VERSION}" > "${app}/beszel_version" \
            || die "${app}: could not write beszel_version"
    fi

    if [ "${WRITE_CHANGELOG}" -eq 1 ]; then
        # Byte-identical to the printf in publish.yml, so a CI regeneration is a
        # no-op instead of a spurious diff.
        printf '# Changelog\n\n[View GitHub release v%s](https://github.com/%s/releases/tag/v%s)\n' \
            "${APP_VERSION}" "${SLUG}" "${APP_VERSION}" > "${app}/CHANGELOG.md" \
            || die "${app}: could not write CHANGELOG.md"
    fi

    if [ -n "${changes## }" ]; then
        pass "${app}:${changes}"
        CHANGED=$((CHANGED + 1))
    else
        pass "${app}: already at ${APP_VERSION}"
    fi
done

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
head1 "Summary"
if [ "${DRY_RUN}" -eq 1 ]; then
    info "${CHANGED} app(s) would change; nothing written"
    exit 0
fi

# All apps share one version number, and a mismatch means Home Assistant cannot
# install whichever app fell behind.
for app in ${APPS}; do
    [ "$(config_version "${app}")" = "${APP_VERSION}" ] \
        || die "${app}: version did not settle at ${APP_VERSION}"
    if [ "${BUMP_BESZEL}" -eq 1 ]; then
        [ "$(pinned_version "${app}")" = "${BESZEL_VERSION}" ] \
            || die "${app}: beszel_version did not settle at ${BESZEL_VERSION}"
    fi
done
pass "all apps report ${APP_VERSION}"

printf '\n  Next: review with %sgit diff%s, then tag the release:\n' "${C_DIM}" "${C_OFF}"
printf '    git commit -am "Bump version to %s"\n' "${APP_VERSION}"
printf '    git tag -a v%s -m "Release v%s" && git push origin v%s\n\n' \
    "${APP_VERSION}" "${APP_VERSION}" "${APP_VERSION}"
