name: "Beszel Agent (Intel GPU)"
description: "Beszel Agent Add-on with Intel GPU and S.M.A.R.T. Monitoring Support"
version: "0.18.8.3"
slug: "beszel-agent-intel"
url: "https://github.com/vineetchoudhary/home-assistant-beszel-agent"
init: false
startup: application
boot: auto
watchdog: "http://[HOST]:[PORT:45877]/cgi-bin/health"
host_network: true
host_pid: true
full_access: true
video: true
docker_api: true
host_dbus: true
privileged:
  - PERFMON
  - SYS_RAWIO
  - SYS_ADMIN
arch:
  - amd64
ports:
  45876/tcp: 45876
  45877/tcp: 45877
ports_description:
  45876/tcp: "Beszel agent SSH listener"
  45877/tcp: "Home Assistant watchdog healthcheck endpoint. Not configurable; if this port is already in use, disable watchdog."
image: "ghcr.io/vineetchoudhary/home-assistant-beszel-agent-intel"
options:
  key: ""
  hub_url: ""
  token: ""
  environment_vars: []
  custom_volumes: []
schema:
  key: password
  hub_url: str
  token: password
  environment_vars:
    - name: str
      value: str
  custom_volumes:
    - host_path: str
      container_path: str
map:
  - type: data
    read_only: false
    path: /var/lib/beszel-agent
